/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-106367-g505a7d39cd-20220321"
#endif /* AVUTIL_FFVERSION_H */
